### ISSUE TITLE
Idempotence issue on Route53 records using create_resources function

### ISSUE THREAD

**Issue by mvisonneau** [puppetlabs/puppetlabs-aws#256]
I'm trying to configure a zone using Hiera and iterating onto my hash with the create_resources function. However I'm facing an issue, all my records keeps getting recreated every time the catalog is applied.

```
Info: Checking if zone example.com. exists
Info: Checking if A record foo.example.com. exists
Info: Creating A record foo.example.com.
Notice: /Stage[main]/Profiles::Dns::Public/Route53_a_record[foo.example.com.]/ensure: created
Info: Updating A record foo.example.com.
Info: Checking if A record bar.example.com. exists
Info: Creating A record bar.example.com.
Notice: /Stage[main]/Profiles::Dns::Public/Route53_a_record[bar.example.com.]/ensure: created
Info: Updating A record bar.example.com.
[..]
```

**Comment by garethr** [comment]
@mvisonneau could you provide more details? Samples of the manifest and example hiera data would be great.

**Comment by mvisonneau** [comment]
I simplified a bit my profile to illustrate :

```puppet
class profiles::dns::public (
  $zones = {},
  $records_a = {},
)  {
  
  validate_hash( $zones )
  validate_hash( $records_a )

  package { ['aws-sdk-core', 'retries']:
    ensure   => present,
    provider => gem,
  }

  $defaults = {
      ensure => present,
  }

  create_resources( route53_zone, $zones, $defaults )
  create_resources( route53_a_record, $records_a, $defaults )
}
```

Here is the hieradata :

```yaml
---
profiles::dns::public::zones:
  example.com.: {}

profiles::dns::public::records_a:
  'foo.example.com.':
    zone: example.com.
    ttl: 300
    values: 127.0.0.1
  'bar.example.com.':
    zone: example.com.
    ttl: 300
    values: 127.0.0.1
```

**Comment by garethr** [comment]
@mvisonneau a couple of things stand out just from observation (so I've not had chance to test these):

* You don't have an explicit `ensure` value
* Values should be an array: https://github.com/puppetlabs/puppetlabs-aws#values

A guess is the latter is triggering a change notification.

**Comment by mvisonneau** [comment]
I unfortunately got the same results with :

```yaml
---
profiles::dns::public::zones:
  example.com.: {}

profiles::dns::public::records_a:
  'foo.example.com.':
    ensure: present
    zone: example.com.
    ttl: 300
    values: [127.0.0.1]
  'bar.example.com.':
    ensure: present
    zone: example.com.
    ttl: 300
    values: [127.0.0.1]
```
